// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw4EGcO_7C448onFce1_fu8uDXBPTtjpk',
    appId: '1:232896256276:web:95ba557b1df6e40ccc4a01',
    messagingSenderId: '232896256276',
    projectId: 'careos-sanctuary-7b2a9',
    authDomain: 'careos-sanctuary-7b2a9.firebaseapp.com',
    storageBucket: 'careos-sanctuary-7b2a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA98U8uS8ki7Tnykx7wNUrjcVVOf0fVAgQ',
    appId: '1:232896256276:android:6f72b0a59709ab15cc4a01',
    messagingSenderId: '232896256276',
    projectId: 'careos-sanctuary-7b2a9',
    storageBucket: 'careos-sanctuary-7b2a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZOcgfasCh1EJz835FjqR2XyHH0bXxZA4',
    appId: '1:232896256276:ios:93cffba48df3b70bcc4a01',
    messagingSenderId: '232896256276',
    projectId: 'careos-sanctuary-7b2a9',
    storageBucket: 'careos-sanctuary-7b2a9.firebasestorage.app',
    iosBundleId: 'com.example.careos',
  );
}
